export const GET_CREDITS = "GET_CREDITS"
export const DELETE_CREDIT = "DELETE_CREDIT"
export const ADD_CREDIT = "ADD_PAYMENT"

export const GET_PAYMENT = "GET_PAYMENT"
export const DELETE_PAYMENT="DELETE_PAYMENT"
export const EDIT_PAYMENT="EDIT_PAYMENT"
export const ADD_MAKE_UPDATE_PAYMENT="ADD_MAKE_PAYMENT"
export const ADD_MAKERESET_UPDATE_PAYMENT="ADD_MAKERESET_PAYMENT"


export const GET_TRANSACTION = "GET_TRANSACTION"
export const ADD_TRANSACTION = "ADD_TRANSACTION"
export const DELETE_TRANSACTION = "DELETE_TRANSACTION"

export const GET_TRANSACTION_STATIC = "GET_TRANSACTION_STATIC"

export const GET_USER= "GET_USER"